### users.getAll
GET http://localhost:8080/users
X-Login: vasya
X-Password: secret

### users.getById
GET http://localhost:8080/users/1
X-Login: vasya
X-Password: secret

### users.create
POST http://localhost:8080/users
X-Login: vasya
X-Password: secret
Content-Type: application/json

{
  "id": 0,
  "login": "anya",
  "password": "password"
}

### users.deleteById
DELETE http://localhost:8080/users/10
X-Login: vasya
X-Password: secret

### users.update
PUT http://localhost:8080/users
X-Login: vasya
X-Password: secret
Content-Type: application/json

{
  "id": 1,
  "login": "vanya",
  "password": "password"
}